### ISSUE TITLE
Self ngrok for multiple client devices ...

### ISSUE THREAD

**Issue by siliconhippy** [tsani/jerrington.me#7]
Hi !

I was directed from this Reddit to your article:
https://www.reddit.com/r/selfhosted/comments/ak63n3/self_hosted_ngrok_alternative/?utm_source=amp&utm_medium=&utm_content=post_body

So I am not technically proficient, but I was looking for an automated solution for multiple client devices behind firewalls ( eg home devices) running a small Linux distro with the Entware repo ( same as for Openwrt for routers.)

Do you think your script can be automated thus, along with letsencrypt certificate automation as well?

Here I am assuming devices cannot be configured manually; they all have the same Linux image with Entware repo, and thus the (bash?) script will need automation. For instance, the device to server SSH login userID/passwords for each device can be preconfigured in the server DB.

**Comment by tsani** [comment]
I think it can be automated as long as you can write some bash and Entware includes ssh. Basically, each firewalled device will need to ssh into the server that is only the public internet and set up the reverse tunnel. The server can reverse proxy different ports, subdirectories, or subdomains into different reverse tunnel ports that are set up by ssh, depending on your needs or preference.

For example firewalled device D0 ssh's into the server and sets up a reverse tunnel on port 5000. Configure nginx on the server to reverse proxy `d0.example.org` into port 5000. Just repeat this configuration for every device Di, but change the reverse tunnel port to 5000 + i.

The main trouble with this setup is that networks are finicky, so ssh may disconnect. You will need to automate a reconnection mechanism. There is the `autossh` program, but I doubt it will come bundled with Entware, so you may need to write an appropriate bash script for the firewalled devices that ssh's in a while loop.

**Comment by siliconhippy** [comment]
Hi Jacob 😊

Thanks for the response. Entware aarch64 repo luckily does have autossh:

http://bin.entware.net/aarch64-k3.10/Packages.html

Otherwise systems script could also be written, as various online tuts
suggest.

An online multi device example:

https://blogs.wcode.org/2015/04/howto-ssh-to-your-iot-device-when-its-behind-a-firewall-or-on-a-3g-dongle/

I was thinking along the same parametrization lines, so nice to have
confirmation !

Cheers 😊
Shippy.
