### ISSUE TITLE
Question about self-hosted-ngrok

### ISSUE THREAD

**Issue by Perzan** [tsani/jerrington.me#9]
Hi Jacob. I recently read your [article](https://jerrington.me/posts/2019-01-29-self-hosted-ngrok.html) and I was considering using this approach. I am a bit of a noob when it comes to cloud servers, so I am curious what host you would use (the one that will be running the server for `tunnel.yourdomain`) or recommend using. Would Amazon Lightsail be a good pick for this?

**Comment by riezahughes** [comment]
I personally went ahead and just used my small little digital ocean server i have. As is mentioned in the article, most people have something to putz around with so i just went that route. :)

**Comment by tsani** [comment]
I can't really speak to LightSail as I've never used it before, but as long as it's something you can ssh into and more or less do whatever, it should be fine. My personal recommendation is DigitalOcean. It's pretty cheap and much simpler than AWS in my experience.
